services:
  web:
    build: .
    container_name: django_app
    command: gunicorn rentbuy.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
