# Generated by Django 5.2 on 2025-04-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_app",
            "0002_alter_user_options_user_role_alter_user_table_cloth_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                blank=True, editable=False, max_length=14, null=True
            ),
        ),
    ]
