# Generated by Django 5.2 on 2025-04-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_transaction_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cloth",
            old_name="name",
            new_name="title",
        ),
    ]
